### ISSUE TITLE
Publish draft

### ISSUE THREAD

**Issue by fulldecent** [buckyos/PublicDataProof#1]
@waterflier ready to publish as draft. If you time it right you can get number 8068.

See: https://github.com/ethereum/EIPs/issues?q=

**Comment by waterflier** [comment]
I already commit PR to ERCs, and get the ERC number :  7585

There is the links:
https://ethereum-magicians.org/t/erc-7585-mixhash-and-public-data-storage-proofs/17707
https://github.com/ethereum/ERCs/pull/177

**Comment by fulldecent** [comment]
Awesome, thank you, I'll comment there and keep the conversation going
